version: 2

build:
   os: "ubuntu-20.04"
   tools:
      python: "3.7"
   jobs:
      pre_build:
      - python brainscore_vision/utils/document_plugins.py

python:
   install:
      - requirements: docs/requirements.txt
