name: brainscore_vision
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.9
  - numpy=1.26.4
  - scipy=1.13.0
  - h5py=3.11.0
  - tqdm=4.66.4
  - gitpython=3.1.43
  - fire=0.6.0
  - jupyter=1.0.0
  - pybtex=0.24.0
  - peewee=3.17.5
  - psycopg2-binary=2.9.9
  - networkx=3.3
  - eva-decord=0.6.1
  - psutil=5.9.8
  - pip:
      - brainscore-core @ git+https://github.com/brain-score/core
      - result-caching @ git+https://github.com/brain-score/result_caching
      - importlib-metadata==4.13.0
      - scikit-learn==1.5.0
      - opencv-python==4.9.0.80
